typography_spectrum: 0.34010738390497863
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2300980305299163
  lightness: 0.5672436838503927
  saturation: 0.22425005678087473
  rhythmicContrast: 0.2603024032432586
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.07602
analytics:
  google: null
  facebook: null
  twitter: null
name: diveLang (David langenmayr)
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ' lanoitanretnI'
purpose: []
