name: diveLang (David langenmayr)
favicon: null
layout_spectrum: 0.6190440466161817
typography_spectrum: 0.34010738390497863
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2300980305299163
  lightness: 0.5672436838503927
  saturation: 0.22425005678087473
  rhythmicContrast: 0.2603024032432586
purpose: []
